#############################################################################
# Makefile for building: pixeleasel
# Generated by qmake (2.01a) (Qt 4.6.3) on: Sun Jul 11 11:40:57 2010
# Project:  pixeleasel.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile pixeleasel.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -L/usr/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		Tool.cpp \
		PenTool.cpp \
		ResizeDialog.cpp \
		Commands.cpp \
		PixelEasel.cpp \
		ImageCanvas.cpp \
		ImageDocument.cpp moc_PixelEasel.cpp \
		moc_ResizeDialog.cpp \
		moc_ImageCanvas.cpp \
		moc_ImageDocument.cpp
OBJECTS       = main.o \
		Tool.o \
		PenTool.o \
		ResizeDialog.o \
		Commands.o \
		PixelEasel.o \
		ImageCanvas.o \
		ImageDocument.o \
		moc_PixelEasel.o \
		moc_ResizeDialog.o \
		moc_ImageCanvas.o \
		moc_ImageDocument.o
DIST          = /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/debug.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		pixeleasel.pro
QMAKE_TARGET  = pixeleasel
DESTDIR       = 
TARGET        = pixeleasel

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: pixeleasel.pro  /usr/share/qt/mkspecs/linux-g++/qmake.conf /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/debug.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile pixeleasel.pro
/usr/share/qt/mkspecs/common/g++.conf:
/usr/share/qt/mkspecs/common/unix.conf:
/usr/share/qt/mkspecs/common/linux.conf:
/usr/share/qt/mkspecs/qconfig.pri:
/usr/share/qt/mkspecs/features/qt_functions.prf:
/usr/share/qt/mkspecs/features/qt_config.prf:
/usr/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/share/qt/mkspecs/features/default_pre.prf:
/usr/share/qt/mkspecs/features/debug.prf:
/usr/share/qt/mkspecs/features/default_post.prf:
/usr/share/qt/mkspecs/features/warn_on.prf:
/usr/share/qt/mkspecs/features/qt.prf:
/usr/share/qt/mkspecs/features/unix/thread.prf:
/usr/share/qt/mkspecs/features/moc.prf:
/usr/share/qt/mkspecs/features/resources.prf:
/usr/share/qt/mkspecs/features/uic.prf:
/usr/share/qt/mkspecs/features/yacc.prf:
/usr/share/qt/mkspecs/features/lex.prf:
/usr/share/qt/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile pixeleasel.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/pixeleasel1.0.0 || $(MKDIR) .tmp/pixeleasel1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/pixeleasel1.0.0/ && $(COPY_FILE) --parents PixelEasel.h Tool.h PenTool.h ResizeDialog.h Commands.h ImageCanvas.h ImageDocument.h .tmp/pixeleasel1.0.0/ && $(COPY_FILE) --parents main.cpp Tool.cpp PenTool.cpp ResizeDialog.cpp Commands.cpp PixelEasel.cpp ImageCanvas.cpp ImageDocument.cpp .tmp/pixeleasel1.0.0/ && (cd `dirname .tmp/pixeleasel1.0.0` && $(TAR) pixeleasel1.0.0.tar pixeleasel1.0.0 && $(COMPRESS) pixeleasel1.0.0.tar) && $(MOVE) `dirname .tmp/pixeleasel1.0.0`/pixeleasel1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/pixeleasel1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_PixelEasel.cpp moc_ResizeDialog.cpp moc_ImageCanvas.cpp moc_ImageDocument.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_PixelEasel.cpp moc_ResizeDialog.cpp moc_ImageCanvas.cpp moc_ImageDocument.cpp
moc_PixelEasel.cpp: ImageDocument.h \
		ImageCanvas.h \
		Tool.h \
		PenTool.h \
		PixelEasel.h
	/usr/bin/moc $(DEFINES) $(INCPATH) PixelEasel.h -o moc_PixelEasel.cpp

moc_ResizeDialog.cpp: ImageDocument.h \
		ImageCanvas.h \
		Tool.h \
		PenTool.h \
		ResizeDialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) ResizeDialog.h -o moc_ResizeDialog.cpp

moc_ImageCanvas.cpp: Tool.h \
		PenTool.h \
		ImageCanvas.h
	/usr/bin/moc $(DEFINES) $(INCPATH) ImageCanvas.h -o moc_ImageCanvas.cpp

moc_ImageDocument.cpp: ImageCanvas.h \
		Tool.h \
		PenTool.h \
		ImageDocument.h
	/usr/bin/moc $(DEFINES) $(INCPATH) ImageDocument.h -o moc_ImageDocument.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp PixelEasel.h \
		ImageDocument.h \
		ImageCanvas.h \
		Tool.h \
		PenTool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Tool.o: Tool.cpp Tool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Tool.o Tool.cpp

PenTool.o: PenTool.cpp PenTool.h \
		Tool.h \
		ImageCanvas.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PenTool.o PenTool.cpp

ResizeDialog.o: ResizeDialog.cpp ResizeDialog.h \
		ImageDocument.h \
		ImageCanvas.h \
		Tool.h \
		PenTool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ResizeDialog.o ResizeDialog.cpp

Commands.o: Commands.cpp Commands.h \
		ImageDocument.h \
		ImageCanvas.h \
		Tool.h \
		PenTool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Commands.o Commands.cpp

PixelEasel.o: PixelEasel.cpp PixelEasel.h \
		ImageDocument.h \
		ImageCanvas.h \
		Tool.h \
		PenTool.h \
		ResizeDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PixelEasel.o PixelEasel.cpp

ImageCanvas.o: ImageCanvas.cpp ImageCanvas.h \
		Tool.h \
		PenTool.h \
		ImageDocument.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ImageCanvas.o ImageCanvas.cpp

ImageDocument.o: ImageDocument.cpp ImageDocument.h \
		ImageCanvas.h \
		Tool.h \
		PenTool.h \
		Commands.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ImageDocument.o ImageDocument.cpp

moc_PixelEasel.o: moc_PixelEasel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_PixelEasel.o moc_PixelEasel.cpp

moc_ResizeDialog.o: moc_ResizeDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ResizeDialog.o moc_ResizeDialog.cpp

moc_ImageCanvas.o: moc_ImageCanvas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ImageCanvas.o moc_ImageCanvas.cpp

moc_ImageDocument.o: moc_ImageDocument.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ImageDocument.o moc_ImageDocument.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

